import { Product } from './types'

export const mockProducts: Product[] = [
  // ─── LIGHTING (15) ───────────────────────────────────────────────────────────
  {
    id: 'l-001',
    slug: 'cattaraugus-brass-center-draft-lamp',
    sku: 'OL-1873-CB',
    patent: '1873 PAT.',
    name: 'Cattaraugus Brass Center-Draft Lamp',
    shortDescription: 'Precision-reproduced center-draft burner on original 1873 patent tooling. Oiled-brass body, borosilicate chimney, No. 2 wick.',
    fullDescription: 'The Cattaraugus is our flagship reproduction — pulled from the same center-draft tooling Bradley & Hubbard patented in 1873. Every brass fitting is hand-fitted in the Pune press shop before the lamp is assembled. The borosilicate chimney is mouth-blown to a tolerance of ±0.4mm. Each lamp runs an 8-hour burn test on No. 2 wick before it earns its numbered tag. There is no second batch. When this crate is empty, it stays empty until we run the dies again.',
    price: 248,
    category: 'lighting',
    burnerSize: 'No. 2',
    material: 'Brass',
    finish: ['Oiled Brass', 'Antique Nickel'],
    fits: 'No. 2 center-draft burner, 7-inch chimney',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-14',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.8 kg',
    images: [
      '/assets/ProductSampleImage1.webp',
      '/assets/HeroSampleImage.webp',
      '/assets/HeroSampleImage4.webp',
      '/assets/HeroSampleImage5.webp',
      '/assets/HeroSampleImage6.webp',
    ],
    inStock: true,
    featured: true,
    collection: 'Cattaraugus Series',
  },
  {
    id: 'l-002',
    slug: 'pittsburgh-railroad-caboose-lamp',
    sku: 'OL-1881-PC',
    patent: '1881 PAT.',
    name: 'Pittsburgh Railroad Caboose Lamp',
    shortDescription: 'Gimbal-mounted caboose lamp based on original 1881 Indian railway order. Cast-iron bracket, brass font, red globe.',
    fullDescription: 'The first batch of gimbal-mounted caboose lamps rolled out of the Pune works in 1881 for the Indian railway. This reproduction uses the original cast-iron bracket patterns and a hand-spun brass font. The red-globe option uses mouth-blown cranberry glass — no tinting, no coating. Bench-tested for 8 hours on No. 1 wick to verify steady gimbal action at 15° list.',
    price: 312,
    category: 'lighting',
    burnerSize: 'No. 1',
    material: 'Cast Iron / Brass',
    finish: ['Black Iron / Brass', 'All Brass'],
    fits: 'No. 1 flat-wick burner, 6-inch globe',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-10',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '2.4 kg',
    images: [],
    inStock: true,
    featured: true,
    collection: 'Railway Series',
  },
  {
    id: 'l-003',
    slug: 'aladdin-mantle-library-lamp',
    sku: 'OL-1902-AL',
    patent: '1902 PAT.',
    name: 'Aladdin Mantle Library Lamp',
    shortDescription: 'Incandescent-mantle oil lamp for desk and reading use. Nickel-plated brass, white cased-glass shade, No. 2 mantle burner.',
    fullDescription: 'The mantle library lamp was the electric light\'s direct competitor in 1902 — brighter, quieter, and more dependable than any early bulb. Our reproduction is built on the same No. 2 mantle burner patterns and fitted with a white cased-glass shade pulled from original molds. The nickel-plated brass body is triple-dipped and buffed by hand.',
    price: 286,
    category: 'lighting',
    burnerSize: 'No. 2',
    material: 'Nickel-Plated Brass',
    finish: ['Nickel', 'Polished Brass'],
    fits: 'No. 2 Aladdin-pattern mantle burner, 10-inch shade',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-08',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.6 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Library Series',
  },
  {
    id: 'l-004',
    slug: 'dietz-no-2-cold-blast-lantern',
    sku: 'OL-1867-DZ',
    patent: '1867 PAT.',
    name: 'Dietz No. 2 Cold-Blast Lantern',
    shortDescription: 'Galvanized-steel cold-blast lantern, reproduction of the 1867 Dietz patent. Tubular wick, clear globe, folding bail handle.',
    fullDescription: 'The cold-blast design pushed fresh air down through the globe and up the chimney — a counterintuitive trick that produced a cleaner, steadier flame than every hot-blast lantern before it. This reproduction is pressed from galvanized steel on the original Dietz dies, fitted with a hand-blown clear globe and a folding bail handle that locks in two positions. Each lantern burns for 11 hours on a full font of No. 1 kerosene.',
    price: 164,
    category: 'lighting',
    burnerSize: 'No. 1',
    material: 'Galvanized Steel',
    finish: ['Galvanized', 'Black Japanned'],
    fits: 'No. 1 tubular wick, 5-inch globe',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-11',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.9 kg',
    images: [],
    inStock: true,
    featured: true,
    collection: 'Dietz Reproductions',
  },
  {
    id: 'l-005',
    slug: 'rochester-brass-parlour-lamp',
    sku: 'OL-1886-RP',
    patent: '1886 PAT.',
    name: 'Rochester Brass Parlour Lamp',
    shortDescription: 'Central-draft parlour lamp with hand-painted opal globe. Polished brass, No. 2 Rochester burner, 12-inch shade fitter.',
    fullDescription: 'The Rochester was the parlour lamp of record from 1886 through the first decade of electrification. The central-draft burner is reproduced from original Rochester patterns; the hand-painted opal globe is produced by two glass workers in Pune who learned the technique from their grandfather\'s notes. This is not a mass-production piece.',
    price: 398,
    category: 'lighting',
    burnerSize: 'No. 2',
    material: 'Polished Brass',
    finish: ['Polished Brass', 'Antique Brass'],
    fits: 'No. 2 Rochester burner, 12-inch shade fitter',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-15',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '2.1 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Parlour Series',
  },
  {
    id: 'l-006',
    slug: 'bradley-hubbard-student-lamp',
    sku: 'OL-1878-BH',
    patent: '1878 PAT.',
    name: 'Bradley & Hubbard Student Lamp',
    shortDescription: 'Double-arm student lamp with counterweighted font. Brass, green cased-glass shade, adjustable arm, No. 2 flat-wick burner.',
    fullDescription: 'The student lamp was designed for long reading hours — the counterweighted font keeps the oil level constant as it empties, maintaining flame height without adjustment. Our B&H reproduction uses the original double-arm casting patterns and is fitted with a green cased-glass shade hand-pressed in Pune. The adjustment mechanism runs on a brass rack with 18 positions.',
    price: 342,
    category: 'lighting',
    burnerSize: 'No. 2',
    material: 'Brass',
    finish: ['Antique Brass', 'Oiled Brass'],
    fits: 'No. 2 flat-wick burner, 10-inch shade',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-12',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.9 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Study Series',
  },
  {
    id: 'l-007',
    slug: 'hanging-hall-lamp-brass',
    sku: 'OL-1893-HH',
    patent: '1893 PAT.',
    name: 'Hanging Hall Lamp — Brass & Opal',
    shortDescription: 'Pendant hall lamp with etched-opal globe, brass fittings, 30-inch drop chain, and a No. 1 burner for low-odour light.',
    fullDescription: 'The hanging hall lamp was the first thing a visitor saw when entering a Victorian home. This reproduction is cast in brass on 1893 patterns and fitted with an etched-opal globe that diffuses light evenly in all directions. The drop chain adjusts from 18 to 48 inches. Supplied with a No. 1 burner and a No. 1 wick — burns clean, burns long.',
    price: 276,
    category: 'lighting',
    burnerSize: 'No. 1',
    material: 'Brass',
    finish: ['Polished Brass', 'Antique Brass'],
    fits: 'No. 1 flat-wick burner, 8-inch globe fitter',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-09',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.4 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Hall & Entry Series',
  },
  {
    id: 'l-008',
    slug: 'miners-safety-lamp-brass',
    sku: 'OL-1815-MS',
    patent: '1815 PAT.',
    name: 'Davy Miners\' Safety Lamp — Brass',
    shortDescription: 'Reproduction Davy safety lamp with fine-mesh gauze chimney. Solid brass body, No. 1 wick, locking bottom cap.',
    fullDescription: 'Humphry Davy\'s 1815 design is the reason underground workers survived the Industrial Revolution. The fine-mesh gauze around the flame prevents ignition of combustible gases while allowing enough air for the flame to burn. Our reproduction is machined in brass from original Davy patterns, with a hand-fitted gauze and a locking bottom cap for safe oil filling.',
    price: 198,
    category: 'lighting',
    burnerSize: 'No. 1',
    material: 'Brass',
    finish: ['Polished Brass'],
    fits: 'No. 1 flat-wick burner, 4-inch gauze chimney',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-07',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.2 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Industrial Heritage',
  },
  {
    id: 'l-009',
    slug: 'banquet-lamp-opaline',
    sku: 'OL-1896-BQ',
    patent: '1896 PAT.',
    name: 'Banquet Lamp — Opaline & Brass',
    shortDescription: 'Tall banquet lamp with hand-blown opaline font and brass pedestal. No. 3 burner, 14-inch shade fitter.',
    fullDescription: 'The banquet lamp was reserved for dining tables and formal drawing rooms — taller, more elaborate, and considerably more expensive than a working lamp. This reproduction uses a hand-blown opaline glass font on a cast-brass pedestal with fluted column. The No. 3 burner is the largest in our range and produces a wide, stable flame suitable for rooms above 4m × 4m.',
    price: 468,
    category: 'lighting',
    burnerSize: 'No. 3',
    material: 'Brass / Opaline Glass',
    finish: ['Polished Brass', 'Ormolu'],
    fits: 'No. 3 central-draft burner, 14-inch shade fitter',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-16',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '3.1 kg',
    images: [],
    inStock: true,
    featured: true,
    collection: 'Formal Dining Series',
  },
  {
    id: 'l-010',
    slug: 'barn-lantern-tin-folded',
    sku: 'OL-1855-BL',
    patent: '1855 PAT.',
    name: 'Barn Lantern — Folded Tin',
    shortDescription: 'Heavy-gauge folded tin barn lantern with pierced-tin ventilation crown and No. 1 flat-wick burner. Wire bail handle.',
    fullDescription: 'The folded-tin barn lantern predates the Dietz patent by twelve years and remains the most practical lantern ever made for outdoor work. Ours is pressed and folded in heavy-gauge tin on original 1855 barn patterns, with a pierced-tin crown for heat venting and a simple wire bail handle that takes a hook. It does not look like a decoration because it is not one.',
    price: 118,
    category: 'lighting',
    burnerSize: 'No. 1',
    material: 'Tin',
    finish: ['Raw Tin', 'Black Japanned'],
    fits: 'No. 1 flat-wick burner, 5-inch globe',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-13',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.7 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Working Lanterns',
  },
  {
    id: 'l-011',
    slug: 'piano-lamp-adjustable-brass',
    sku: 'OL-1905-PL',
    patent: '1905 PAT.',
    name: 'Piano Lamp — Adjustable Brass',
    shortDescription: 'Adjustable-arm piano lamp in polished brass. Telescoping stem, No. 2 flat-wick burner, green cased-glass shade.',
    fullDescription: 'Designed to illuminate the sheet music without glare on the performer\'s face, the piano lamp is one of the most precise pieces of Victorian lighting engineering. The telescoping stem adjusts from 24 to 42 inches; the shade angle is adjustable by 45°. Our reproduction uses the original 1905 adjustment mechanism patterns, still machined in the Pune shop.',
    price: 318,
    category: 'lighting',
    burnerSize: 'No. 2',
    material: 'Polished Brass',
    finish: ['Polished Brass'],
    fits: 'No. 2 flat-wick burner, 10-inch shade',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-10',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.7 kg',
    images: [],
    inStock: false,
    featured: false,
    collection: 'Study Series',
  },
  {
    id: 'l-012',
    slug: 'coach-lamp-pair-brass',
    sku: 'OL-1862-CL',
    patent: '1862 PAT.',
    name: 'Coach Lamp — Brass (Pair)',
    shortDescription: 'Matched pair of coach lamps with bevelled glass panels and brass frames. No. 1 burners, wall-bracket mountings included.',
    fullDescription: 'The coach lamp started on carriage doors and migrated to gatepost and hallway sconce by 1870. Our matched pair is cast from 1862 coach patterns with four-panel bevelled glass and a brass frame that is soldered, not stamped. Wall-bracket mountings are included. Pair pricing — these do not sell separately.',
    price: 524,
    category: 'lighting',
    burnerSize: 'No. 1',
    material: 'Brass / Bevelled Glass',
    finish: ['Polished Brass', 'Antique Brass'],
    fits: 'No. 1 flat-wick burner, 6-inch globe',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-08',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '2.8 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Entry & Exterior',
  },
  {
    id: 'l-013',
    slug: 'hurricane-lamp-pressed-glass',
    sku: 'OL-1848-HU',
    patent: '1848 PAT.',
    name: 'Hurricane Lamp — Pressed Glass',
    shortDescription: 'Low table hurricane lamp with hand-pressed glass dome and iron base. No. 1 flat-wick burner, suitable for outdoor use.',
    fullDescription: 'The hurricane lamp was designed for a single purpose: to keep a flame alive in wind. The pressed-glass dome seals around the base and the air supply is controlled through two calibrated side vents. Our reproduction uses original 1848 pressed-glass molds and a hand-poured iron base with a ring foot. It will burn in a Force 4 wind without adjustment.',
    price: 142,
    category: 'lighting',
    burnerSize: 'No. 1',
    material: 'Iron / Pressed Glass',
    finish: ['Black Iron'],
    fits: 'No. 1 flat-wick burner, pressed-glass dome 8-inch',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-14',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.3 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Working Lanterns',
  },
  {
    id: 'l-014',
    slug: 'tiffany-style-kerosene-floor-lamp',
    sku: 'OL-1899-TF',
    patent: '1899 PAT.',
    name: 'Tiffany-Pattern Floor Lamp — Brass & Slag Glass',
    shortDescription: 'Tall floor lamp on tripod base with slag-glass shade. Brass column, No. 3 central-draft burner, 16-inch shade fitter.',
    fullDescription: 'The slag-glass shade is not produced on original Tiffany patterns — the Tiffany studio name belongs to another house. What we offer is a floor lamp built on the same 1899 structural patterns that made floor-standing oil lamps viable, fitted with a slag-glass shade produced by the only surviving workshop in the region that still uses the poured-slab method.',
    price: 586,
    category: 'lighting',
    burnerSize: 'No. 3',
    material: 'Brass / Slag Glass',
    finish: ['Antique Brass'],
    fits: 'No. 3 central-draft burner, 16-inch shade fitter',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-11',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '4.2 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Formal Dining Series',
  },
  {
    id: 'l-015',
    slug: 'wall-sconce-bracket-lamp',
    sku: 'OL-1890-WS',
    patent: '1890 PAT.',
    name: 'Wall-Sconce Bracket Lamp — Nickel',
    shortDescription: 'Swing-arm wall sconce with nickel-plated brass bracket and white porcelain reflector. No. 1 flat-wick burner.',
    fullDescription: 'The wall sconce bracket lamp was the workhouse of Victorian domestic lighting — installed in corridors, dressing rooms, and kitchens where a table lamp was impractical. The swing arm rotates 180° and locks in four positions. The porcelain reflector behind the flame doubles the effective light output without increasing fuel consumption.',
    price: 194,
    category: 'lighting',
    burnerSize: 'No. 1',
    material: 'Nickel-Plated Brass',
    finish: ['Nickel', 'Antique Brass'],
    fits: 'No. 1 flat-wick burner, 7-inch chimney',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-09',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.1 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Hall & Entry Series',
  },

  // ─── GLASS & CHIMNEYS (12) ────────────────────────────────────────────────
  {
    id: 'g-001',
    slug: 'clear-beaded-chimney-7-inch',
    sku: 'GC-CB7-CLR',
    patent: 'TRADE PATTERN',
    name: 'Clear Beaded Chimney — 7-inch',
    shortDescription: 'Mouth-blown borosilicate chimney with beaded-top rim. Fits No. 2 burner. Tolerance ±0.4mm.',
    fullDescription: 'Every chimney we sell is mouth-blown, not machine-pressed. The beaded top rim on this 7-inch chimney is the original Victorian method for protecting the lip from thermal shock. Blown to a ±0.4mm fit tolerance for No. 2 burners — including Cattaraugus, Rochester, and standard flat-wick patterns. Sold individually.',
    price: 38,
    category: 'glass-chimneys',
    burnerSize: 'No. 2',
    material: 'Borosilicate Glass',
    finish: ['Clear'],
    fits: 'No. 2 burner — 7-inch nominal chimney',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-05',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.18 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Standard Chimneys',
  },
  {
    id: 'g-002',
    slug: 'milk-white-cased-shade-10-inch',
    sku: 'GC-MW10-WH',
    patent: 'TRADE PATTERN',
    name: 'Milk-White Cased Shade — 10-inch',
    shortDescription: 'Hand-blown milk-white cased-glass shade. Smooth outer, opaline inner layer. 10-inch shade fitter.',
    fullDescription: 'Milk-white casing is the highest-quality glass finish for lamp shades — a double-layer blown technique where a clear glass gather is cased in opaline white before being blown to shape. The result is a diffused light that is softer than any single-layer shade. Our 10-inch version fits standard No. 2 parlour and student lamp shade fitters.',
    price: 72,
    category: 'glass-chimneys',
    burnerSize: 'No. 2',
    material: 'Cased Glass',
    finish: ['Milk White'],
    fits: '10-inch shade fitter — No. 2 parlour lamps',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-06',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.42 kg',
    images: [],
    inStock: true,
    featured: true,
    collection: 'Shade Collection',
  },
  {
    id: 'g-003',
    slug: 'cranberry-cut-crystal-shade',
    sku: 'GC-CK-CRN',
    patent: 'TRADE PATTERN',
    name: 'Cranberry Cut-Crystal Shade',
    shortDescription: 'Mouth-blown cranberry glass shade with 24 hand-cut facets. 10-inch shade fitter. One of twelve in this crate.',
    fullDescription: 'Cranberry glass gets its colour from gold chloride introduced during the blowing process — there is no tinting or coating. Each shade is blown by a single glass worker and hand-cut with 24 facets using a wheel-grinding technique unchanged since 1870. This crate contains twelve shades; no two are identical. The weight and colour depth vary by ±8% between pieces — this is not a defect.',
    price: 148,
    category: 'glass-chimneys',
    burnerSize: 'No. 2',
    material: 'Cranberry Glass',
    finish: ['Cranberry Cut'],
    fits: '10-inch shade fitter — No. 2 parlour lamps',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-07',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.52 kg',
    images: [],
    inStock: true,
    featured: true,
    collection: 'Shade Collection',
  },
  {
    id: 'g-004',
    slug: 'clear-beaded-chimney-6-inch',
    sku: 'GC-CB6-CLR',
    patent: 'TRADE PATTERN',
    name: 'Clear Beaded Chimney — 6-inch',
    shortDescription: 'Mouth-blown borosilicate chimney, beaded-top rim. Fits No. 1 burner. Tolerance ±0.4mm.',
    fullDescription: 'The 6-inch chimney for No. 1 flat-wick burners — lanterns, wall sconces, and working lamps that burn on a smaller wick. Same mouth-blown borosilicate glass and beaded rim as our 7-inch version, sized to ±0.4mm for No. 1 burner collars.',
    price: 34,
    category: 'glass-chimneys',
    burnerSize: 'No. 1',
    material: 'Borosilicate Glass',
    finish: ['Clear'],
    fits: 'No. 1 burner — 6-inch nominal chimney',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-04',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.14 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Standard Chimneys',
  },
  {
    id: 'g-005',
    slug: 'etched-floral-chimney-7-inch',
    sku: 'GC-EF7-ETH',
    patent: 'TRADE PATTERN',
    name: 'Etched Floral Chimney — 7-inch',
    shortDescription: 'Acid-etched floral-panel chimney in clear borosilicate. Hand-etched in three panels. Fits No. 2 burner.',
    fullDescription: 'Acid etching on lamp chimneys was a Victorian luxury — it diffuses the flame light into a patterned glow without reducing luminance. Each panel of this 7-inch chimney is etched by hand using a paper-resist technique, creating a relief floral pattern that is different on every piece. Fits No. 2 burner collars to ±0.4mm tolerance.',
    price: 58,
    category: 'glass-chimneys',
    burnerSize: 'No. 2',
    material: 'Borosilicate Glass',
    finish: ['Acid Etched Clear'],
    fits: 'No. 2 burner — 7-inch nominal chimney',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-05',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.19 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Decorated Chimneys',
  },
  {
    id: 'g-006',
    slug: 'green-cased-shade-12-inch',
    sku: 'GC-GN12-GRN',
    patent: 'TRADE PATTERN',
    name: 'Green Cased-Glass Shade — 12-inch',
    shortDescription: 'Hand-blown green cased-glass shade for parlour and student lamps. 12-inch shade fitter. Chrome-oxide colouring.',
    fullDescription: 'The desk-lamp shade is green for a reason — the chrome-oxide colouring filters blue-spectrum light and reduces visual fatigue during long reading sessions. This is a genuine cased-glass piece: the green layer is blown over a clear inner gather. Not coated, not tinted. Fits 12-inch shade fitters on No. 2 and No. 3 parlour and student lamps.',
    price: 88,
    category: 'glass-chimneys',
    burnerSize: 'No. 3',
    material: 'Cased Glass',
    finish: ['Chrome-Oxide Green'],
    fits: '12-inch shade fitter — No. 2/3 student and parlour lamps',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-06',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.48 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Shade Collection',
  },
  {
    id: 'g-007',
    slug: 'opal-chimney-8-inch-large',
    sku: 'GC-OP8-OPL',
    patent: 'TRADE PATTERN',
    name: 'Opal Chimney — 8-inch Large',
    shortDescription: 'Large opaline chimney for No. 3 central-draft and mantle burners. Mouth-blown, ±0.5mm fit tolerance.',
    fullDescription: 'The largest chimney in our range — 8 inches tall, blown to fit No. 3 central-draft burners including Rochester, Banquet, and Aladdin mantle patterns. The opaline body softens the harshest parts of a mantle flame\'s spectrum. Blown to ±0.5mm rather than ±0.4mm due to the larger diameter.',
    price: 48,
    category: 'glass-chimneys',
    burnerSize: 'No. 3',
    material: 'Opaline Glass',
    finish: ['Opal'],
    fits: 'No. 3 burner — 8-inch nominal chimney',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-04',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.22 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Standard Chimneys',
  },
  {
    id: 'g-008',
    slug: 'cobalt-blue-globe-6-inch',
    sku: 'GC-CB6-BLU',
    patent: 'TRADE PATTERN',
    name: 'Cobalt Blue Globe — 6-inch',
    shortDescription: 'Mouth-blown cobalt-blue globe for lanterns and coach lamps. 6-inch diameter. Cobalt-oxide colouring, no tinting.',
    fullDescription: 'Cobalt glass is coloured with cobalt oxide introduced into the melt — the same method used for cobalt glass since the 1820s. No spraying, no coating. Our 6-inch globe is blown for No. 1 lantern and coach-lamp fitters. The deep blue makes these globes useful as signal lamps as well as decorative pieces.',
    price: 44,
    category: 'glass-chimneys',
    burnerSize: 'No. 1',
    material: 'Cobalt Glass',
    finish: ['Cobalt Blue'],
    fits: 'No. 1 lantern globe fitter — 6-inch nominal',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-05',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.28 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Coloured Globes',
  },
  {
    id: 'g-009',
    slug: 'amber-ribbed-shade-10-inch',
    sku: 'GC-AR10-AMB',
    patent: 'TRADE PATTERN',
    name: 'Amber Ribbed Shade — 10-inch',
    shortDescription: 'Amber pressed-glass shade with vertical ribs. 10-inch shade fitter. Iron-oxide colouring.',
    fullDescription: 'The ribbed amber shade is one of the simpler pieces in this crate and one of the hardest to reproduce accurately — the vertical ribs require a two-part mold pressed from inside the gather while it is still plastic. Iron-oxide amber, no tinting. Fits standard 10-inch shade fitters.',
    price: 64,
    category: 'glass-chimneys',
    burnerSize: 'No. 2',
    material: 'Pressed Glass',
    finish: ['Amber Ribbed'],
    fits: '10-inch shade fitter',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-06',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.38 kg',
    images: [],
    inStock: false,
    featured: false,
    collection: 'Shade Collection',
  },
  {
    id: 'g-010',
    slug: 'student-lamp-shade-white-10-inch',
    sku: 'GC-SW10-WH',
    patent: 'TRADE PATTERN',
    name: 'Student Lamp Shade — White Opaline, 10-inch',
    shortDescription: 'Replacement opaline shade for student lamps. Flat-bottom fitter collar, 10-inch. Mouth-blown single-layer opaline.',
    fullDescription: 'Student-lamp shades have a flat-bottom collar and a closed top — different from the open parlour shade. This 10-inch replacement fits Bradley & Hubbard, Manhattan, and Rochester student lamp fitters. Single-layer mouth-blown opaline glass, not cased. Sold individually.',
    price: 54,
    category: 'glass-chimneys',
    burnerSize: 'No. 2',
    material: 'Opaline Glass',
    finish: ['White Opaline'],
    fits: 'Student lamp shade collar — 10-inch flat-bottom fitter',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-04',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.32 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Shade Collection',
  },
  {
    id: 'g-011',
    slug: 'hand-painted-rose-shade-12-inch',
    sku: 'GC-PR12-PNT',
    patent: 'TRADE PATTERN',
    name: 'Hand-Painted Rose Shade — 12-inch',
    shortDescription: 'Mouth-blown opaline shade with hand-painted rose-and-vine motif. 12-inch shade fitter. No two identical.',
    fullDescription: 'The hand-painting is done in enamels fired onto the glass surface — not printed, not decal-applied. Two painters in the Pune glass works divide the motif between them: one paints the vine and bud placement, the second fills the rose faces. Each shade takes approximately 4 hours of painting time and a second kiln firing. No two are identical. We sell twelve; that is all there are.',
    price: 176,
    category: 'glass-chimneys',
    burnerSize: 'No. 3',
    material: 'Painted Opaline Glass',
    finish: ['Hand-Painted Rose'],
    fits: '12-inch shade fitter — No. 3 parlour and banquet lamps',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-07',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.56 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Shade Collection',
  },
  {
    id: 'g-012',
    slug: 'clear-globe-5-inch-lantern',
    sku: 'GC-CG5-CLR',
    patent: 'TRADE PATTERN',
    name: 'Clear Globe — 5-inch Lantern',
    shortDescription: 'Plain mouth-blown clear globe for barn lanterns and cold-blast lanterns. 5-inch diameter.',
    fullDescription: 'The replacement globe for cold-blast lanterns, barn lanterns, and any 5-inch globe fitter. Plain clear borosilicate glass — no decoration, no pattern. Blown to ±0.4mm tolerance. Supplied individually; sold in sets of four on request.',
    price: 28,
    category: 'glass-chimneys',
    burnerSize: 'No. 1',
    material: 'Borosilicate Glass',
    finish: ['Clear'],
    fits: '5-inch globe fitter — barn and cold-blast lanterns',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-03',
    workshop: 'Pune Glass Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.12 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Standard Chimneys',
  },

  // ─── HARDWARE (10) ────────────────────────────────────────────────────────
  {
    id: 'h-001',
    slug: 'no-2-center-draft-burner',
    sku: 'HW-B2-CD',
    patent: '1873 PAT.',
    name: 'No. 2 Center-Draft Burner',
    shortDescription: 'Replacement center-draft burner on 1873 Cattaraugus patent tooling. Brass, No. 2 wick tube, bayonet chimney collar.',
    fullDescription: 'The center-draft burner that anchors our entire fixtures line — now available as a standalone replacement part. Machined in the Pune press shop on the original 1873 tooling. Fits all No. 2 font collars including Cattaraugus, Hinks, and Rochester pattern bases. Includes a No. 2 cotton wick.',
    price: 48,
    category: 'hardware',
    burnerSize: 'No. 2',
    material: 'Brass',
    finish: ['Oiled Brass'],
    fits: 'No. 2 font collar — Cattaraugus, Hinks, Rochester patterns',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-10',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.22 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Burners & Wicks',
  },
  {
    id: 'h-002',
    slug: 'no-1-flat-wick-burner',
    sku: 'HW-B1-FW',
    patent: '1867 PAT.',
    name: 'No. 1 Flat-Wick Burner',
    shortDescription: 'Standard No. 1 flat-wick burner. Brass, spring-loaded wick adjuster, beaded chimney collar. Fits all No. 1 font collars.',
    fullDescription: 'The No. 1 flat-wick burner is the most widely produced kerosene burner pattern in history — every lamp manufacturer had a version. Ours is machined on 1867 patterns with a spring-loaded wick adjuster that advances the wick smoothly without backlash. Fits Dietz, Rayo, and all standard No. 1 font collars.',
    price: 36,
    category: 'hardware',
    burnerSize: 'No. 1',
    material: 'Brass',
    finish: ['Polished Brass'],
    fits: 'No. 1 font collar — Dietz, Rayo, standard patterns',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-09',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.18 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Burners & Wicks',
  },
  {
    id: 'h-003',
    slug: 'no-3-central-draft-burner',
    sku: 'HW-B3-CD',
    patent: '1896 PAT.',
    name: 'No. 3 Central-Draft Burner',
    shortDescription: 'Large No. 3 central-draft burner for banquet and floor lamps. Brass, dual-tube construction, 14-inch shade collar.',
    fullDescription: 'The No. 3 central-draft burner is the largest oil-lamp burner in regular production. The dual-tube construction draws air through both the inner and outer flame paths, producing a wide, stable flame suitable for large rooms. Fits Banquet, Rochester No. 3, and floor-lamp font collars. Includes No. 3 cotton wick.',
    price: 64,
    category: 'hardware',
    burnerSize: 'No. 3',
    material: 'Brass',
    finish: ['Antique Brass'],
    fits: 'No. 3 font collar — Banquet, Rochester No. 3, floor lamps',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-11',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.34 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Burners & Wicks',
  },
  {
    id: 'h-004',
    slug: 'cotton-wick-no-2-pack-6',
    sku: 'HW-WK2-6PK',
    patent: 'SUPPLY ITEM',
    name: 'No. 2 Cotton Wick — Pack of 6',
    shortDescription: 'Braided-cotton flat wick for No. 2 burners. 7/8-inch width, 12-inch length. Pack of 6.',
    fullDescription: 'Woven from 100% combed cotton on a braided-core loom — no synthetic fibres. The 7/8-inch width is the correct specification for No. 2 burners including Cattaraugus, Hinks, and Rochester center-draft patterns. Each wick delivers approximately 40 hours of burn time before trimming becomes necessary.',
    price: 18,
    category: 'hardware',
    burnerSize: 'No. 2',
    material: 'Cotton',
    finish: ['Natural Cotton'],
    fits: 'No. 2 burner — 7/8-inch wick tube',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-03',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.08 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Burners & Wicks',
  },
  {
    id: 'h-005',
    slug: 'font-cap-brass-no-2',
    sku: 'HW-FC2-BR',
    patent: 'SUPPLY ITEM',
    name: 'Brass Font Cap — No. 2 Thread',
    shortDescription: 'Replacement brass font cap for No. 2 threaded lamp bases. O-ring sealed. Fits all standard No. 2 font threads.',
    fullDescription: 'A simple but critical part — the font cap seals the oil reservoir and holds the burner. O-ring sealed at the thread shoulder to prevent fuel seepage. Machined from brass rod stock in the Pune shop. Fits all standard No. 2 lamp fonts with a right-hand thread.',
    price: 14,
    category: 'hardware',
    burnerSize: 'No. 2',
    material: 'Brass',
    finish: ['Brass'],
    fits: 'No. 2 right-hand thread font collar',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-05',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.06 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Operational Parts',
  },
  {
    id: 'h-006',
    slug: 'chimney-holder-spring-clip',
    sku: 'HW-CH-SC',
    patent: 'SUPPLY ITEM',
    name: 'Chimney Holder — Spring-Clip Brass',
    shortDescription: 'Replacement spring-clip chimney holder in brass. Fits all standard No. 1 and No. 2 burner gallery rings.',
    fullDescription: 'The spring-clip chimney holder is the part most likely to fail on a working lamp — it flexes with every heating and cooling cycle. Ours is machined from spring-tempered brass rather than stamped from sheet; the spring tension remains consistent after 500+ cycles in our test bench.',
    price: 22,
    category: 'hardware',
    burnerSize: 'Universal',
    material: 'Spring-Tempered Brass',
    finish: ['Brass'],
    fits: 'Universal — No. 1 and No. 2 gallery rings',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-08',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.04 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Operational Parts',
  },
  {
    id: 'h-007',
    slug: 'wick-trimmer-scissors-brass',
    sku: 'HW-WT-SC',
    patent: '1872 PAT.',
    name: 'Wick-Trimmer Scissors — Brass',
    shortDescription: 'Curved-blade wick-trimming scissors with attached snuffer tray. Cast brass, 1872 pattern.',
    fullDescription: 'Wick-trimming scissors have a curved blade that cuts the charred wick top cleanly without disturbing the wick position. The snuffer tray catches the trimmed carbon so it does not fall into the oil font. Cast in brass on 1872 patterns with a pivot pin that adjusts to three spring tensions.',
    price: 42,
    category: 'hardware',
    burnerSize: null,
    material: 'Cast Brass',
    finish: ['Polished Brass', 'Antique Brass'],
    fits: 'Universal — all flat-wick burners',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-04',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.14 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Operational Parts',
  },
  {
    id: 'h-008',
    slug: 'no-1-cotton-wick-pack-6',
    sku: 'HW-WK1-6PK',
    patent: 'SUPPLY ITEM',
    name: 'No. 1 Cotton Wick — Pack of 6',
    shortDescription: 'Braided-cotton flat wick for No. 1 burners. 5/8-inch width, 10-inch length. Pack of 6.',
    fullDescription: 'The No. 1 wick for Dietz, Rayo, and all standard No. 1 flat-wick burners. 5/8-inch width, 100% combed cotton, no synthetic fibres. 40-hour burn time per trim.',
    price: 14,
    category: 'hardware',
    burnerSize: 'No. 1',
    material: 'Cotton',
    finish: ['Natural Cotton'],
    fits: 'No. 1 burner — 5/8-inch wick tube',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-03',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.06 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Burners & Wicks',
  },
  {
    id: 'h-009',
    slug: 'brass-font-filler-funnel',
    sku: 'HW-FF-BR',
    patent: 'SUPPLY ITEM',
    name: 'Brass Font-Filler Funnel',
    shortDescription: 'Long-neck brass funnel for filling lamp fonts without spillage. Removable filter screen.',
    fullDescription: 'The long-neck funnel keeps kerosene away from the exterior lamp surfaces during filling. The removable screen at the neck filters any sediment before it enters the font — sediment is the primary cause of wick clogging. Machined from brass tubing in the Pune shop. A simple thing; a useful thing.',
    price: 28,
    category: 'hardware',
    burnerSize: null,
    material: 'Brass',
    finish: ['Brass'],
    fits: 'Universal — all lamp fonts',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-05',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.09 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Operational Parts',
  },
  {
    id: 'h-010',
    slug: 'no-2-aladdin-mantle',
    sku: 'HW-AM2-MNT',
    patent: '1902 PAT.',
    name: 'No. 2 Aladdin Mantle — Pack of 3',
    shortDescription: 'Replacement incandescent mantles for No. 2 Aladdin-pattern mantle burners. Thoriated cotton, pre-burned. Pack of 3.',
    fullDescription: 'Pre-burned mantles are critical — a new, unburned mantle will not produce full light output and will deteriorate unevenly if not ignited correctly on first use. Our mantles are pre-burned in the Pune shop on a reference burner, inspected, and packed individually. They are fragile; handle them as such. Pack of 3.',
    price: 24,
    category: 'hardware',
    burnerSize: 'No. 2',
    material: 'Thoriated Cotton',
    finish: ['Pre-Burned'],
    fits: 'No. 2 Aladdin-pattern mantle burner',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-06',
    workshop: 'Pune Press Shop 4',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.02 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Burners & Wicks',
  },

  // ─── SIGNS (13) ──────────────────────────────────────────────────────────
  {
    id: 's-001',
    slug: 'coleman-lantern-co-porcelain-sign',
    sku: 'SN-COL-24',
    patent: '1934 PROCESS',
    name: 'Coleman Lantern Co. — Porcelain Sign, 24-inch',
    shortDescription: 'Triple-fired reproduction porcelain advertising sign for Coleman Lantern Co. 24×18-inch. Flanged steel backer.',
    fullDescription: 'Our porcelain signs are triple-fired — the ground coat, the colour coat, and the clear protective coat each go through a separate kiln cycle at 820°C. This is the process developed in the Pune works in 1934 for the advertising-sign trade and it is the same process we use today. The flanged steel backer is pressed and drilled for four mounting points. Weather-resistant, UV-stable.',
    price: 148,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain'],
    fits: '24×18-inch — 4-point wall or fence mount',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-12',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '2.1 kg',
    images: [],
    inStock: true,
    featured: true,
    collection: 'Lantern & Lamp Trade Signs',
  },
  {
    id: 's-002',
    slug: 'railway-crossing-reflector-sign',
    sku: 'SN-RWY-18',
    patent: '1881 PAT.',
    name: 'Railway Crossing Reflector Sign — 18-inch',
    shortDescription: 'Reproduction railway crossing warning sign with tin reflector insert. 18×12-inch, black on white porcelain, original 1881 design.',
    fullDescription: 'The original railway crossing signs in India combined a painted warning with a tin-foil reflector insert that caught a lantern\'s beam at night. Our reproduction preserves both elements: triple-fired porcelain lettering and a hand-cut tin reflector inlaid in the centre panel. The reflector is replaceable. 18×12-inch, four-hole mount.',
    price: 128,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain / Tin Reflector'],
    fits: '18×12-inch — 4-point mount',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-13',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.8 kg',
    images: [],
    inStock: true,
    featured: true,
    collection: 'Railway Series Signs',
  },
  {
    id: 's-003',
    slug: 'acme-lamp-sign-co-dealer-sign',
    sku: 'SN-ACM-36',
    patent: '1934 PROCESS',
    name: 'Acme Lamp & Sign Co. — Dealer Sign, 36-inch',
    shortDescription: 'Authorised dealer sign for Acme Lamp & Sign Co. Triple-fired porcelain, brass-flanged, 36×12-inch.',
    fullDescription: 'The dealer sign that hung in every hardware shop that stocked our lamps between 1934 and 1967. We have four original reference pieces; this reproduction is taken directly from the surviving 1948 example with the cleanest remaining enamel. Triple-fired, brass-flanged steel backer. 36×12-inch. A piece of our own history.',
    price: 188,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain'],
    fits: '36×12-inch — 4-point wall mount',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-14',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '3.2 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Acme Archive Signs',
  },
  {
    id: 's-004',
    slug: 'kerosene-oil-dealer-flange-sign',
    sku: 'SN-KER-24',
    patent: '1934 PROCESS',
    name: 'Kerosene Oil Dealer — Flanged Sign, 24-inch',
    shortDescription: 'Double-sided flanged porcelain sign for kerosene oil retailers. 24×18-inch per side. Red on cream.',
    fullDescription: 'The flanged double-sided sign was mounted perpendicular to the shop front — it could be read from either direction along the street. This reproduction is taken from the 1934 standard design used by kerosene wholesalers throughout the subcontinent. Red on cream, triple-fired, flanged for 45mm projecting bracket or direct post mount.',
    price: 218,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain — Double-Sided'],
    fits: '24×18-inch — flanged projecting bracket',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-11',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '2.8 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Trade Signs',
  },
  {
    id: 's-005',
    slug: 'dietz-lanterns-porcelain-sign',
    sku: 'SN-DTZ-24',
    patent: '1934 PROCESS',
    name: 'Dietz Lanterns — Porcelain Sign, 24-inch',
    shortDescription: 'Triple-fired porcelain reproduction Dietz Lanterns advertising sign. 24×18-inch, blue on white.',
    fullDescription: 'Dietz Lanterns ran a substantial advertising campaign for dealers in the first decades of the 20th century. This 24-inch reproduction is taken from a 1921 dealer-supply catalogue reference — blue on white, triple-fired, 24×18-inch. Flanged steel backer with four-hole mount.',
    price: 148,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain'],
    fits: '24×18-inch — 4-point wall mount',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-10',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '2.1 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Lantern & Lamp Trade Signs',
  },
  {
    id: 's-006',
    slug: 'standard-oil-co-pump-sign',
    sku: 'SN-STD-18',
    patent: '1934 PROCESS',
    name: 'Standard Oil Co. — Pump Plate Sign, 18-inch',
    shortDescription: 'Oval pump-plate porcelain sign, Standard Oil Co. Red and white. 18-inch diameter. Four-hole mount.',
    fullDescription: 'Standard Oil\'s pump-plate sign is one of the most collectible petroleum signs in the world — which is why we are not selling an original. This is a triple-fired reproduction taken from archive reference photography, not from a surviving example. It is marked on the reverse as a reproduction. 18-inch oval, four-hole mount.',
    price: 164,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain'],
    fits: '18-inch oval — 4-point mount',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-09',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.4 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Petroleum Trade Signs',
  },
  {
    id: 's-007',
    slug: 'no-smoking-kerosene-store-sign',
    sku: 'SN-NSM-12',
    patent: '1934 PROCESS',
    name: 'No Smoking — Kerosene Store Sign, 12-inch',
    shortDescription: 'Small square porcelain safety sign for kerosene storage areas. Black on yellow. 12×12-inch.',
    fullDescription: 'Safety signage was a legal requirement in kerosene storage areas from the 1880s. The black-on-yellow warning colour scheme was standardised across the British Indian colonial supply chain. Our 12×12-inch reproduction is taken from a Pune warehouse sign dating to 1912. Triple-fired, flanged steel backer.',
    price: 88,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain'],
    fits: '12×12-inch — 2-point or 4-point wall mount',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-08',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.9 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Industrial Safety Signs',
  },
  {
    id: 's-008',
    slug: 'aladdin-mantle-lamps-dealer-sign',
    sku: 'SN-ALD-36',
    patent: '1934 PROCESS',
    name: 'Aladdin Mantle Lamps — Dealer Sign, 36-inch',
    shortDescription: 'Aladdin Mantle Lamps authorised dealer sign. Triple-fired porcelain, 36×12-inch. Green and gold.',
    fullDescription: 'Aladdin ran a distinctive green-and-gold dealer sign programme in the 1920s. This reproduction is taken from a surviving Adelaide hardware store example held in a private collection. Photographed and reproduced with the owner\'s permission. Triple-fired, flanged steel backer, 36×12-inch.',
    price: 188,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain'],
    fits: '36×12-inch — 4-point wall mount',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-07',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '3.2 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Lantern & Lamp Trade Signs',
  },
  {
    id: 's-009',
    slug: 'patel-brothers-hardware-sign',
    sku: 'SN-PTL-24',
    patent: '1934 PROCESS',
    name: 'Patel Brothers Hardware — Custom Sign, 24-inch',
    shortDescription: 'Reproduction of the original Patel Brothers Hardware shop sign, Pune, circa 1938. Triple-fired porcelain.',
    fullDescription: 'We have one surviving photograph of the Patel Brothers Hardware shop in Pune, circa 1938. The sign is partially obscured by a bullock cart. We reproduced what we could read and left the rest as a deliberate blank in the design. It is not a complete reproduction of a complete sign. It is a piece of our own workshop history, imperfect and actual.',
    price: 168,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain'],
    fits: '24×18-inch — 4-point wall mount',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-14',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '2.1 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Acme Archive Signs',
  },
  {
    id: 's-010',
    slug: 'b-p-kerosene-round-sign',
    sku: 'SN-BPK-24',
    patent: '1934 PROCESS',
    name: 'B.P. Kerosene — Round Sign, 24-inch',
    shortDescription: 'Round double-sided porcelain forecourt sign for B.P. Kerosene. 24-inch diameter. Triple-fired, flanged bracket.',
    fullDescription: 'British Petroleum ran a distinctive round forecourt sign programme for kerosene dealers from the 1940s. This reproduction is taken from an original example held in the BP Heritage Collection and reproduced under the terms of their public archive access policy. Triple-fired, double-sided, 24-inch diameter, flanged for projecting bracket mount.',
    price: 234,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain — Double-Sided'],
    fits: '24-inch round — flanged projecting bracket',
    benchTesterName: 'Meera Joshi',
    benchTestDate: '2026-03-10',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '3.4 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Petroleum Trade Signs',
  },
  {
    id: 's-011',
    slug: 'adelaide-house-street-plaque',
    sku: 'SN-ADL-14',
    patent: '1934 PROCESS',
    name: 'Adelaide House — Street Number Plaque',
    shortDescription: 'Reproduction of 14 Pirie Street building plaque. Cast porcelain, house number and street name, 14×8-inch.',
    fullDescription: 'The house number plaque at 14 Pirie Street has been replaced three times since 1898. This reproduction is cast from the third plaque (circa 1934) still installed on the building. Black number on cream ground, single-fired with a clear glaze. 14×8-inch, two-hole mount. A small piece; a specific one.',
    price: 68,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain',
    finish: ['Single-Fired Porcelain'],
    fits: '14×8-inch — 2-point wall mount',
    benchTesterName: 'S. Bhattacharya',
    benchTestDate: '2026-03-06',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '0.6 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Acme Archive Signs',
  },
  {
    id: 's-012',
    slug: 'petroleum-hazard-diamond-sign',
    sku: 'SN-PHZ-18',
    patent: '1934 PROCESS',
    name: 'Petroleum Hazard Diamond — Industrial Sign, 18-inch',
    shortDescription: 'NFPA-style petroleum hazard diamond, reproduction industrial porcelain sign. 18×18-inch, red/yellow/white.',
    fullDescription: 'The NFPA hazard diamond is a 20th-century safety standard, but the Pune works produced a precursor version for petroleum storage since 1934. Our 18-inch square reproduction follows the 1934 Pune design, not the modern NFPA standard — the colour codes differ slightly. Triple-fired, four-hole mount.',
    price: 112,
    category: 'signs',
    burnerSize: null,
    material: 'Porcelain on Steel',
    finish: ['Triple-Fired Porcelain'],
    fits: '18×18-inch — 4-point mount',
    benchTesterName: 'T. Krishnaswamy',
    benchTestDate: '2026-03-08',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.6 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Industrial Safety Signs',
  },
  {
    id: 's-013',
    slug: 'victorian-lamp-post-plate',
    sku: 'SN-VLP-12',
    patent: '1873 PAT.',
    name: 'Victorian Lamp-Post Plate — Cast Iron',
    shortDescription: 'Cast-iron lamp-post identification plate, 1873 design. Street number, parish or district name, 12×4-inch.',
    fullDescription: 'The Victorian municipal lamp-post plate identified the street, district, and lamp number for the lamp-lighter\'s route. Cast in iron from original 1873 pattern plates, each is sand-cast and hand-finished in the Pune foundry. Supplied blank — letters and numbers are inlaid by the buyer from a supplied set of cast-iron characters. A working piece for those who want to mark something precisely.',
    price: 96,
    category: 'signs',
    burnerSize: null,
    material: 'Cast Iron',
    finish: ['Black Iron'],
    fits: '12×4-inch — inset mounting or surface mount',
    benchTesterName: 'R.K. Patel',
    benchTestDate: '2026-03-12',
    workshop: 'Pune Sign Works',
    edition: 'Spring 2026 — Crate No. 014',
    netWeight: '1.4 kg',
    images: [],
    inStock: true,
    featured: false,
    collection: 'Municipal & Street Signs',
  },
]
