import { Product } from './types'

export const mockProducts: Product[] = [
  {
    id: 'eb-001',
    slug: 'oil-lamp-shade-floral-etched-large-ball-shade-blue-4-fit',
    sku: 'EB-204895',
    patent: '',
    name: 'OIL LAMP SHADE - Floral Etched Large Ball Shade Blue 4" Fit',
    shortDescription: 'Oil Lamp Shade - Floral Etched Large Ball  Blue  4" fit',
    fullDescription: 'Oil Lamp Shade - Floral Etched Large Ball  Blue  4" fit\n\nDimensions — Base (Outer Diameter): 4" fit  /  10cm · Top (Outer Diameter): 3" / 8cm · Width (At widest): 7.5"\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.',
    price: 135.85,
    category: 'oil-lamp-shades',
    burnerSize: 'No. 3',
    stockQuantity: 1,
    material: 'original antique shade of Victorian period',
    finish: [],
    fits: 'Base (Outer Diameter): 4" fit  /  10cm · Top (Outer Diameter): 3" / 8cm · Width (At widest): 7.5"',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/aKwAAOSwkhZj2HR9/s-l1600.webp',
    ],
    inStock: true,
    featured: true,
    collection: '',
  },
  {
    id: 'eb-002',
    slug: 'oil-lamp-shade-open-tulip-etched-shade-magenta-4-fit',
    sku: 'EB-208628',
    patent: '',
    name: 'OIL LAMP SHADE - Open Tulip Etched Shade Magenta 4" Fit',
    shortDescription: 'Oil / Kerosene Lamp Open Tulip Etched Shade - Cranberry / Magenta 4" fit',
    fullDescription: 'Oil / Kerosene Lamp Open Tulip Etched Shade - Cranberry / Magenta 4" fit\n\nDimensions — Base (Outer Diameter): 4" fit  /  10cm · Top (Outer Diameter): 5  3/4"\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.',
    price: 135.85,
    category: 'oil-lamp-shades',
    burnerSize: 'No. 2',
    stockQuantity: 1,
    material: 'original antique shade of Victorian period',
    finish: [],
    fits: 'Base (Outer Diameter): 4" fit  /  10cm · Top (Outer Diameter): 5  3/4"',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/p78AAOSw6DZj2dIb/s-l1600.webp',
      'https://i.ebayimg.com/images/g/9-4AAOSwJyxj2dIm/s-l1600.png',
      'https://i.ebayimg.com/images/g/p78AAOSw6DZj2dIb/s-l1600.png',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-003',
    slug: 'oil-lamp-wick-flat-cotton-wick-7-8-1-metre',
    sku: 'EB-101111',
    patent: '',
    name: 'OIL LAMP WICK- Flat cotton wick 7/8"  (1 metre)',
    shortDescription: 'Flat Cotton Wick 7/8 "',
    fullDescription: 'Flat Cotton Wick 7/8 "\n\nDimensions — Length: 1 Metre',
    price: 5.72,
    category: 'oil-lamp-spreaders',
    burnerSize: null,
    stockQuantity: 1,
    material: '',
    finish: [],
    fits: 'Length: 1 Metre',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/zm0AAOSwL7VWlycM/s-l1600.webp',
      'https://i.ebayimg.com/images/g/zm0AAOSwL7VWlycM/s-l1600.jpg',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-004',
    slug: 'oil-lamp-wick-duplex-wick-1-1-16-1-metre',
    sku: 'EB-956526',
    patent: '',
    name: 'OIL LAMP WICK- Duplex Wick 1  1/16"   (1 metre)',
    shortDescription: 'Duplex Wick 1 1/16 " — For use in Duplex twin side by side burners.',
    fullDescription: 'Duplex Wick 1 1/16 "\nFor use in Duplex twin side by side burners.\n\nDimensions — Length: 1 meter',
    price: 7.87,
    category: 'oil-lamp-spreaders',
    burnerSize: null,
    stockQuantity: 1,
    material: '',
    finish: [],
    fits: 'Length: 1 meter',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/VQcAAOSwFqJWmEKr/s-l1600.webp',
      'https://i.ebayimg.com/images/g/VQcAAOSwFqJWmEKr/s-l1600.jpg',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-005',
    slug: 'oil-lamp-pressure-lamp-glass-tilley-171-glass-for-tilley-pressur',
    sku: 'EB-210261',
    patent: '',
    name: 'OIL LAMP PRESSURE LAMP GLASS  Tilley 171 Glass for Tilley Pressure Lamp',
    shortDescription: 'Pressure Lamp Glass - Tilley 171. Made from high heat resistant Borosilicate Glass.',
    fullDescription: 'Oil Lamp Pressure Lamp Glass - Tilley 171\nMade from high heat resistant Borosilicate Glass\n\nDimensions — Base Opening Diameter: 2" / 50mm · Top Opening Diameter: 1 7/8" / 48mm\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.',
    price: 35.75,
    category: 'oil-lamp-shades',
    burnerSize: 'No. 2',
    stockQuantity: 1,
    material: 'high heat resistant Borosilicate Glass',
    finish: [],
    fits: 'Tilley 246 Pressure Lamp',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/AAEAAOSwLYlj2dL4/s-l1600.webp',
      'https://i.ebayimg.com/images/g/AAEAAOSwLYlj2dL4/s-l1600.png',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-006',
    slug: 'oil-lamp-shade-vesta-shade-7-3-8-cupid-etched-green',
    sku: 'EB-390452',
    patent: '',
    name: 'OIL LAMP SHADE - Vesta Shade 7 3/8"  Cupid Etched Green',
    shortDescription: 'Vesta Shade 7 3/8" Cupid Etched Glass — Green. Original antique style of the Victorian period.',
    fullDescription: 'Oil Lamp Shade - Vesta Shade 7 3/8"  Cupid Etched Glass - Green\n\nDimensions — Base (Outer Diameter): 7 3/8"   /  18.5cm  fit · Top (Outer Diameter): 4" · Width (At widest): 8 1/4"\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.',
    price: 92.95,
    category: 'oil-lamp-shades',
    burnerSize: null,
    stockQuantity: 1,
    material: 'original antique shade of Victorian period',
    finish: [],
    fits: 'Base (Outer Diameter): 7 3/8"   /  18.5cm  fit · Top (Outer Diameter): 4" · Width (At widest): 8 1/4"',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/T-MAAOSwEjFXfF-6/s-l1600.webp',
      'https://i.ebayimg.com/images/g/7BIAAOSwkl5XfF~r/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/WKEAAOSwEjFXfGAg/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/gmcAAOSwRQlXfGBb/s-l1600.jpg',
    ],
    inStock: true,
    featured: true,
    collection: '',
  },
  {
    id: 'eb-007',
    slug: 'oil-lamp-pressure-lamp-glass-handi-glass-for-handi-pressure-lamp',
    sku: 'EB-306601',
    patent: '',
    name: 'OIL LAMP PRESSURE LAMP GLASS. Handi Glass for Handi Pressure Lamp',
    shortDescription: 'Pressure Lamp Glass for the Handi — one of the very few pressure lamps made in Australia, built by Handiworks Pty of Brisbane, registered 1933.',
    fullDescription: 'Oil Lamp Pressure Lamp Glass- Handi\nThe Handi pressure lamp is one of the very few pressure lamps made in Australia and certainly forms part of the history of Australia.  It was built by the Handiworks Pty of Brisbane which was registered in 1933 with their first lantern going on sale in 1936.\nMade from high temperature Borosilicate Glass\n\nDimensions — Base (Outer Diameter): 3  7/8" · Top (Outer Diameter): 3  7/8"\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.',
    price: 35.75,
    category: 'oil-lamp-shades',
    burnerSize: null,
    stockQuantity: 1,
    material: 'high temperature Borosilicate Glass',
    finish: [],
    fits: 'Handi Pressure Lamp',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/A0gAAOSwxj5XQaCd/s-l1600.webp',
      'https://i.ebayimg.com/images/g/AYoAAOSwfY9XQaC2/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/57UAAOSwintXSmGj/s-l1600.jpg',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-008',
    slug: 'oil-lamp-chimney-kosmos-chimney-6-ligne-1-5-16-clear-tall',
    sku: 'EB-365903',
    patent: '',
    name: "OIL LAMP CHIMNEY- Kosmos Chimney 6''' (ligne)  1  5/16\"  Clear,  Tall",
    shortDescription: "Kosmos Oil Lamp Chimney 6''' (ligne)  1  5/16\"  Clear glass, Tall.",
    fullDescription: "Kosmos Oil Lamp Chimney\nKosmos Oil Lamp Chimney 6 ''' (ligne)  1  5/16\"  Clear glass, Tall.\n\nDimensions — Base (Outer Diameter): 1  5/16 \" · Top (Outer Diameter): 1\"\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.",
    price: 21.45,
    category: 'oil-lamp-shades',
    burnerSize: 'No. 1',
    stockQuantity: 1,
    material: '',
    finish: [],
    fits: 'Base (Outer Diameter): 1  5/16" · Top (Outer Diameter): 1"',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/1Z4AAOSw5IJWclvN/s-l1600.webp',
      'https://i.ebayimg.com/images/g/1Z4AAOSw5IJWclvN/s-l1600.jpg',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-009',
    slug: 'oil-lamp-spreader-miller-flame-spreader-1',
    sku: 'EB-950466',
    patent: '',
    name: 'OIL LAMP SPREADER- Miller Flame Spreader #1',
    shortDescription: 'Miller Oil Lamp Flame Spreader #1 — Brass construction.',
    fullDescription: 'Miller Oil Lamp Flame Spreader #1\nBrass\n\nDimensions — Top diameter: 1 1/8" · Bottom diameter: 1"',
    price: 25.03,
    category: 'oil-lamp-spreaders',
    burnerSize: 'No. 1',
    stockQuantity: 1,
    material: 'Brass',
    finish: [],
    fits: 'Top diameter: 1 1/8" · Bottom diameter: 1"',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/UCEAAOSwCypWmw8r/s-l1600.webp',
      'https://i.ebayimg.com/images/g/vqYAAOSwvUlWtABR/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/UCEAAOSwCypWmw8r/s-l1600.jpg',
    ],
    inStock: true,
    featured: true,
    collection: '',
  },
  {
    id: 'eb-010',
    slug: 'oil-lamp-chimney-kosmos-chimney-6-ligne-1-5-16-clear-short',
    sku: 'EB-219496',
    patent: '',
    name: "OIL LAMP CHIMNEY- Kosmos Chimney 6''' (ligne)  1  5/16\"  Clear,  Short",
    shortDescription: "Kosmos Oil Lamp Chimney 6''' (ligne)  1  5/16\"  Clear glass, Short.",
    fullDescription: "Kosmos Oil Lamp Chimney\nKosmos Oil Lamp Chimney 6 ''' (ligne)  1  5/16\"  Clear glass, short.\n\nDimensions — Base (Outer Diameter): 1  5/16 \" · Top (Outer Diameter): 1\"\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.",
    price: 21.45,
    category: 'oil-lamp-shades',
    burnerSize: 'No. 1',
    stockQuantity: 1,
    material: '',
    finish: [],
    fits: 'Base (Outer Diameter): 1  5/16" · Top (Outer Diameter): 1"',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/OSgAAOSwNyFWcls2/s-l1600.webp',
      'https://i.ebayimg.com/images/g/OSgAAOSwNyFWcls2/s-l1600.jpg',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-011',
    slug: 'oil-lamp-shade-vesta-shade-7-3-8-cupid-etched-blue',
    sku: 'EB-401972',
    patent: '',
    name: 'OIL LAMP SHADE - Vesta Shade 7 3/8"  Cupid Etched Blue',
    shortDescription: 'Vesta Shade 7 3/8" Cupid Etched Glass — Blue. Original antique style of the Victorian period.',
    fullDescription: 'Oil Lamp Shade - Vesta Shade 7 3/8"  Cupid Etched Glass - Blue\n\nDimensions — Base (Outer Diameter): 7 3/8"  / 18.5cm fit · Top (Outer Diameter): 4" · Width (At widest): 8 1/4"\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.',
    price: 92.95,
    category: 'oil-lamp-shades',
    burnerSize: null,
    stockQuantity: 1,
    material: 'original antique shade of Victorian period',
    finish: [],
    fits: 'Base (Outer Diameter): 7 3/8"  / 18.5cm fit · Top (Outer Diameter): 4" · Width (At widest): 8 1/4"',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/Y-IAAOSwwo1XfGK-/s-l1600.webp',
      'https://i.ebayimg.com/images/g/pdYAAOSwhOVXfGLq/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/apkAAOSwwo1XfGMN/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/vCkAAOSwRQlXfGNH/s-l1600.jpg',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-012',
    slug: 'oil-lamp-shade-vesta-shade-7-3-8-cupid-etched-amethyst',
    sku: 'EB-397349',
    patent: '',
    name: 'OIL LAMP SHADE - Vesta Shade 7 3/8"  Cupid Etched  Amethyst',
    shortDescription: 'Vesta Shade 7 3/8" Cupid Etched Glass — Amethyst. Original antique style of the Victorian period.',
    fullDescription: 'Oil Lamp Shade - Vesta Shade 7 3/8"  Cupid Etched Glass - Amethyst\n\nDimensions — Base (Outer Diameter): 7 3/8"  /  18.5cm  fit · Top (Outer Diameter): 4" · Width (At widest): 8 1/4"\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.',
    price: 92.95,
    category: 'oil-lamp-shades',
    burnerSize: null,
    stockQuantity: 1,
    material: 'original antique shade of Victorian period',
    finish: [],
    fits: 'Base (Outer Diameter): 7 3/8"  /  18.5cm  fit · Top (Outer Diameter): 4" · Width (At widest): 8 1/4"',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/x3oAAOSwbYZXfGGx/s-l1600.webp',
      'https://i.ebayimg.com/images/g/mgQAAOSwRQlXfGF~/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/gQkAAOSwhOVXfGFB/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/E5UAAOSwkl5XfGHm/s-l1600.jpg',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-013',
    slug: 'oil-lamp-book-oil-kerosene-lamps-by-peter-cuffley-2004',
    sku: 'EB-042515',
    patent: '',
    name: 'OIL LAMP BOOK - "Oil & Kerosene Lamps" by Peter Cuffley  2004',
    shortDescription: '"Oil & Kerosene Lamps" by Peter Cuffley — the definitive reference book for non-electric lamp collectors. Latest hardcover edition 2004.',
    fullDescription: 'Oil Lamp Book - "Oil & Kerosene Lamps"\nby Peter Cuffley\nlatest edition 2004\nPublished by The Oil Lamp Company\nThe Bible of Lamp Collecting!\nTHE Reference Book for non-electric Lamps.... for both the seasoned Collector, and for those just starting out.\nThis is the latest hardcover Edition, which was published by The Oil Lamp Company of Melbourne in 2004, which has added colour photograph pages not in the previous editions.',
    price: 46.48,
    category: 'oil-lamp-chimneys',
    burnerSize: null,
    stockQuantity: 1,
    material: '',
    finish: [],
    fits: '',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '2004',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/REoAAOSw8btd5sTy/s-l1600.webp',
      'https://i.ebayimg.com/images/g/RPQAAOSwuMNd5sT8/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/LZEAAOSwuOJd5sUF/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/r00AAOSwGyZd5sUR/s-l1600.jpg',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-014',
    slug: 'oil-lamp-pressure-lamp-glass-tilley-182-glass-for-tilley-pressur',
    sku: 'EB-211963',
    patent: '',
    name: 'OIL LAMP PRESSURE LAMP GLASS   Tilley 182 Glass for Tilley Pressure Lamp',
    shortDescription: 'Pressure Lamp Glass - Tilley 182. Made from high heat resistant Borosilicate Glass.',
    fullDescription: 'Oil Lamp Pressure Lamp Glass - Tilley 182 Glass\nMade from high heat resistant Borosilicate Glass\n\nDimensions — Base Opening  Diameter: 1 7/8" / 48mm · Top Opening Diameter: 3 3/8" / 85mm\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.',
    price: 35.75,
    category: 'oil-lamp-shades',
    burnerSize: null,
    stockQuantity: 1,
    material: 'high heat resistant Borosilicate Glass',
    finish: [],
    fits: 'Tilley Table & Inspection Pressure Lamps',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/zkoAAOSwcDJj2dNa/s-l1600.webp',
      'https://i.ebayimg.com/images/g/zkoAAOSwcDJj2dNa/s-l1600.png',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-015',
    slug: 'oil-lamp-shade-vesta-shade-7-3-8-cupid-etched-peach',
    sku: 'EB-129368',
    patent: '',
    name: 'OIL LAMP SHADE - Vesta Shade 7 3/8"  Cupid Etched Peach',
    shortDescription: 'Vesta Shade 7 3/8" Cupid Etched Glass — Peach. Original antique style of the Victorian period.',
    fullDescription: 'Oil Lamp Shade - Vesta Shade 7 3/8"  Cupid Etched Glass - Peach\n\nDimensions — Base (Outer Diameter): 7 3/8"  /  18.5cm fit · Top (Outer Diameter): 4" · Width (At widest): 8 1/4"\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.',
    price: 92.95,
    category: 'oil-lamp-shades',
    burnerSize: null,
    stockQuantity: 1,
    material: 'original antique shade of Victorian period',
    finish: [],
    fits: 'Base (Outer Diameter): 7 3/8"  /  18.5cm fit · Top (Outer Diameter): 4" · Width (At widest): 8 1/4"',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/ESEAAOSwhOVXeI9s/s-l1600.webp',
      'https://i.ebayimg.com/images/g/MskAAOSwgY9XeI-c/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/yNAAAOSwEjFXeI~V/s-l1600.jpg',
      'https://i.ebayimg.com/images/g/ESEAAOSwhOVXeI9s/s-l1600.jpg',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
  {
    id: 'eb-016',
    slug: 'oil-lamp-chimney-miller-no-3-jumbo-chimney-3-3-4-clear',
    sku: 'EB-986046',
    patent: '',
    name: 'OIL LAMP CHIMNEY- Miller No. 3 Jumbo Chimney 3 3/4"  Clear',
    shortDescription: 'Miller No. 3 Jumbo Chimney 3 3/4" Clear — fits Miller No. 3 burners.',
    fullDescription: 'Miller No. 3  Chimney\nMiller No. 3 Chimney 3 3/4"  Clear\n\nDimensions — Base (Outer Diameter): 3 3/4"  /  9.5cm · Top (Outer Diameter): 2 1/2"\n\nOccasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass.\nThese reflect the individuality or these hand made items.',
    price: 42.9,
    category: 'oil-lamp-shades',
    burnerSize: 'No. 3',
    stockQuantity: 1,
    material: '',
    finish: [],
    fits: 'Miller No. 3 Burners',
    benchTesterName: '',
    benchTestDate: '',
    workshop: '',
    edition: '',
    netWeight: '',
    era: '',
    powerSource: '',
    productType: '',
    condition: '',
    style: '',
    colour: '',
    brand: '',
    vintage: '',
    images: [
      'https://i.ebayimg.com/images/g/PuMAAOSw41xXO8QC/s-l1600.webp',
      'https://i.ebayimg.com/images/g/PuMAAOSw41xXO8QC/s-l1600.jpg',
    ],
    inStock: true,
    featured: false,
    collection: '',
  },
]
