import {
  AdminOrder,
  AdminProduct,
  AdminCollection,
  AdminCustomer,
  ChartDataPoint,
  RevenueStats,
  TopProduct,
  AbandonedCheckout,
} from './types'

export const MOCK_ADMIN_PASSWORD = 'acme2026'

export function getOrderByTrackingRef(ref: string): AdminOrder | undefined {
  return mockOrders.find(o => o.trackingRef === ref)
}

// ─── Orders ──────────────────────────────────────────────────────────────────

export const mockOrders: AdminOrder[] = [
  {
    id: 'ORD-1001',
    customer: {
      name: 'Margaret Holloway',
      email: 'margaret@example.com',
      phone: '+1 902 555 0142',
      address: '14 Elm Street',
      city: 'Halifax',
      province: 'Nova Scotia',
      country: 'Canada',
    },
    date: '2026-05-27',
    items: [
      { id: 'i1', title: 'Embossed Satin Glass Shade — Powder Blue', sku: 'ACM-001', quantity: 1, unitPrice: 175.00, image: '' },
      { id: 'i2', title: 'No. 2 Duplex Burner Wick', sku: 'ACM-011', quantity: 2, unitPrice: 18.00, image: '' },
    ],
    subtotal: 211.00,
    shipping: 18.50,
    tax: 28.19,
    total: 257.69,
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    notes: '',
    trackingRef: 'ACME-1001-NS',
    estimatedDelivery: '30 May 2026',
    fulfillmentEvents: [
      { id: 'fe-1001-1', status: 'confirmed', message: 'Payment verified, packing begins.', happenedAt: '2026-05-27T10:00:00Z' },
    ],
  },
  {
    id: 'ORD-1002',
    customer: {
      name: 'James Whitfield',
      email: 'james.whitfield@example.com',
      phone: '+1 902 555 0198',
      address: '7 Harbour View',
      city: 'Dartmouth',
      province: 'Nova Scotia',
      country: 'Canada',
    },
    date: '2026-05-26',
    items: [
      { id: 'i3', title: 'Open Tulip Etched Shade — Magenta', sku: 'ACM-002', quantity: 1, unitPrice: 175.00, image: '' },
    ],
    subtotal: 175.00,
    shipping: 14.00,
    tax: 23.31,
    total: 212.31,
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    notes: 'Please wrap carefully — gift.',
    trackingRef: 'ACME-2614-NS',
    estimatedDelivery: '28 May 2026',
    fulfillmentEvents: [
      { id: 'fe-1002-1', status: 'confirmed',      message: 'Payment verified, packing begins.',                            happenedAt: '2026-05-26T09:00:00Z' },
      { id: 'fe-1002-2', status: 'label_printed',  message: 'Straw-packed and hand-numbered by our bench team.',            happenedAt: '2026-05-26T14:30:00Z' },
      { id: 'fe-1002-3', status: 'in_transit',     message: 'Collected by Canada Post Express freight.',                    happenedAt: '2026-05-27T08:45:00Z', trackingNumber: 'CA123456789CA', carrier: 'Canada Post — Express' },
      { id: 'fe-1002-4', status: 'delivered',      message: 'Left with resident. Signed for by J. W.',                     happenedAt: '2026-05-28T11:20:00Z' },
    ],
  },
  {
    id: 'ORD-1003',
    customer: {
      name: 'Eleanor Vance',
      email: 'eleanor.v@example.com',
      phone: '+1 416 555 0177',
      address: '22 Queen Street W',
      city: 'Toronto',
      province: 'Ontario',
      country: 'Canada',
    },
    date: '2026-05-25',
    items: [
      { id: 'i4', title: 'Butterfly Beehive Shade — Cranberry', sku: 'ACM-003', quantity: 1, unitPrice: 190.00, image: '' },
    ],
    subtotal: 190.00,
    shipping: 16.00,
    tax: 25.35,
    total: 231.35,
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    notes: '',
    trackingRef: 'ACME-2591-ON',
    estimatedDelivery: '28 May 2026',
    fulfillmentEvents: [
      { id: 'fe-1003-1', status: 'confirmed',      message: 'Payment verified, packing begins.',                            happenedAt: '2026-05-25T10:15:00Z' },
      { id: 'fe-1003-2', status: 'label_printed',  message: 'Straw-packed and hand-numbered by our bench team.',            happenedAt: '2026-05-26T13:00:00Z' },
      { id: 'fe-1003-3', status: 'in_transit',     message: 'Collected by Canada Post Express freight.',                    happenedAt: '2026-05-27T09:00:00Z', trackingNumber: 'CA987654321CA', carrier: 'Canada Post — Express' },
      { id: 'fe-1003-4', status: 'delivered',      message: 'Left at front door. Photo on file.',                           happenedAt: '2026-05-28T14:05:00Z' },
    ],
  },
  {
    id: 'ORD-1004',
    customer: {
      name: 'Robert Dunning',
      email: 'rdunning@example.com',
      phone: '+1 604 555 0131',
      address: '88 Granville St',
      city: 'Vancouver',
      province: 'British Columbia',
      country: 'Canada',
    },
    date: '2026-05-24',
    items: [
      { id: 'i5', title: 'No. 1 Round Wick — Cotton', sku: 'ACM-012', quantity: 4, unitPrice: 12.00, image: '' },
      { id: 'i6', title: 'Brass Gallery Ring — 4 inch', sku: 'ACM-008', quantity: 1, unitPrice: 34.00, image: '' },
    ],
    subtotal: 82.00,
    shipping: 10.00,
    tax: 10.93,
    total: 102.93,
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    notes: '',
    trackingRef: 'ACME-1004-BC',
    estimatedDelivery: '29 May 2026',
    fulfillmentEvents: [
      { id: 'fe-1004-1', status: 'confirmed',     message: 'Payment verified, packing begins.',                             happenedAt: '2026-05-24T11:30:00Z' },
      { id: 'fe-1004-2', status: 'label_printed', message: 'Straw-packed and hand-numbered by our bench team.',             happenedAt: '2026-05-25T15:00:00Z' },
    ],
  },
  {
    id: 'ORD-1005',
    customer: {
      name: 'Patricia Lowry',
      email: 'patricia.lowry@example.com',
      phone: '+1 514 555 0109',
      address: '3 Rue Saint-Denis',
      city: 'Montreal',
      province: 'Quebec',
      country: 'Canada',
    },
    date: '2026-05-22',
    items: [
      { id: 'i7', title: 'Oil Lamp Collector — Volume 2', sku: 'ACM-015', quantity: 1, unitPrice: 48.00, image: '' },
    ],
    subtotal: 48.00,
    shipping: 8.00,
    tax: 6.40,
    total: 62.40,
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    notes: '',
    trackingRef: 'ACME-2540-QC',
    estimatedDelivery: '26 May 2026',
    fulfillmentEvents: [
      { id: 'fe-1005-1', status: 'confirmed',     message: 'Payment verified, packing begins.',                             happenedAt: '2026-05-22T09:45:00Z' },
      { id: 'fe-1005-2', status: 'label_printed', message: 'Straw-packed and hand-numbered by our bench team.',             happenedAt: '2026-05-23T14:00:00Z' },
      { id: 'fe-1005-3', status: 'in_transit',    message: 'Collected by Purolator standard freight.',                      happenedAt: '2026-05-24T08:30:00Z', trackingNumber: 'PUR456789123CA', carrier: 'Purolator — Standard' },
      { id: 'fe-1005-4', status: 'delivered',     message: 'Delivered to mailbox.',                                         happenedAt: '2026-05-26T10:45:00Z' },
    ],
  },
  {
    id: 'ORD-1006',
    customer: {
      name: 'William Hartley',
      email: 'w.hartley@example.com',
      phone: '+1 780 555 0188',
      address: '51 Jasper Avenue',
      city: 'Edmonton',
      province: 'Alberta',
      country: 'Canada',
    },
    date: '2026-05-20',
    items: [
      { id: 'i8', title: 'Embossed Satin Glass Shade — Powder Blue', sku: 'ACM-001', quantity: 1, unitPrice: 175.00, image: '' },
    ],
    subtotal: 175.00,
    shipping: 14.00,
    tax: 23.31,
    total: 212.31,
    paymentStatus: 'refunded',
    fulfillmentStatus: 'cancelled',
    notes: 'Customer requested cancellation before dispatch.',
    trackingRef: 'ACME-1006-AB',
    fulfillmentEvents: [
      { id: 'fe-1006-1', status: 'confirmed', message: 'Payment verified, packing begins.',                                  happenedAt: '2026-05-20T10:00:00Z' },
    ],
  },
  {
    id: 'ORD-1007',
    customer: {
      name: 'Sylvia Brennan',
      email: 'sylvia.b@example.com',
      phone: '+1 902 555 0162',
      address: '9 Spring Garden Rd',
      city: 'Halifax',
      province: 'Nova Scotia',
      country: 'Canada',
    },
    date: '2026-05-18',
    items: [
      { id: 'i9', title: 'Aladdin Pressure Lamp — Complete', sku: 'ACM-005', quantity: 1, unitPrice: 320.00, image: '' },
    ],
    subtotal: 320.00,
    shipping: 22.00,
    tax: 42.66,
    total: 384.66,
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    notes: '',
    trackingRef: 'ACME-1007-NS',
    estimatedDelivery: '22 May 2026',
    fulfillmentEvents: [
      { id: 'fe-1007-1', status: 'confirmed',     message: 'Payment verified, packing begins.',                             happenedAt: '2026-05-18T09:00:00Z' },
      { id: 'fe-1007-2', status: 'label_printed', message: 'Straw-packed and hand-numbered by our bench team.',             happenedAt: '2026-05-19T14:00:00Z' },
      { id: 'fe-1007-3', status: 'in_transit',    message: 'Collected by Canada Post Express freight.',                     happenedAt: '2026-05-20T08:15:00Z', trackingNumber: 'CA654321987CA', carrier: 'Canada Post — Express' },
      { id: 'fe-1007-4', status: 'delivered',     message: 'Left with resident. Signed for by S. B.',                       happenedAt: '2026-05-22T13:30:00Z' },
    ],
  },
  {
    id: 'ORD-1008',
    customer: {
      name: 'Thomas Ashby',
      email: 'tashby@example.com',
      phone: '+1 613 555 0145',
      address: '120 Wellington St',
      city: 'Ottawa',
      province: 'Ontario',
      country: 'Canada',
    },
    date: '2026-05-15',
    items: [
      { id: 'i10', title: 'Nickel Spreader — No. 2 Fit', sku: 'ACM-009', quantity: 2, unitPrice: 28.00, image: '' },
    ],
    subtotal: 56.00,
    shipping: 10.00,
    tax: 7.46,
    total: 73.46,
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    notes: '',
    trackingRef: 'ACME-1008-ON',
    estimatedDelivery: '19 May 2026',
    fulfillmentEvents: [
      { id: 'fe-1008-1', status: 'confirmed',     message: 'Payment verified, packing begins.',                             happenedAt: '2026-05-15T10:30:00Z' },
      { id: 'fe-1008-2', status: 'label_printed', message: 'Straw-packed and hand-numbered by our bench team.',             happenedAt: '2026-05-16T15:00:00Z' },
      { id: 'fe-1008-3', status: 'in_transit',    message: 'Collected by Canada Post standard freight.',                    happenedAt: '2026-05-17T09:00:00Z', trackingNumber: 'CA321654987CA', carrier: 'Canada Post — Standard' },
      { id: 'fe-1008-4', status: 'delivered',     message: 'Delivered to front desk. Signed for by T. A.',                  happenedAt: '2026-05-19T11:00:00Z' },
    ],
  },
]

// ─── Products ─────────────────────────────────────────────────────────────────

export const mockAdminProducts: AdminProduct[] = [
  {
    id: 'sp-001',
    title: 'Embossed Satin Glass Shade — Powder Blue 5 1/4"',
    category: { id: 'col-2', name: 'Oil Lamp Shades' },   // oil-lamp-shades
    shortDescription: 'A superb reproduction made in the tradition of the original antique shade of Victorian period.',
    fullDescription: 'A superb reproduction made in the tradition of the original antique shade of Victorian period. This shade will fit a shade ring of dimensions 5 1/4" as seen on small lamps such as Piano / Peg Lamps. Occasional bubbles, specks and ripples within the surface sometimes exist in hand blown or handcrafted glass. These reflect the individuality of these hand made items.',
    price: 175.00,
    compareAtPrice: null,
    sku: 'ACM-001',
    patent: '',
    stock: 5,
    status: 'active',
    collections: ['oil-lamp-shades'],
    tags: ['featured'],
    vendor: 'Acme Lamp & Sign Co.',
    images: [],
    sellWhenOutOfStock: false,
    netWeight: '0.4 kg',
    material: 'Glass',
    colour: 'Powder Blue',
    style: 'Victorian',
    brand: 'The Oil Lamp Company',
    vintage: 'Reproduction',
    burnerSize: '',
    fits: '5 1/4" shade ring',
    era: 'Victorian',
    powerSource: 'Oil',
    productType: 'Shade',
    condition: 'New',
    edition: '',
    workshop: '',
    benchTester: '',
    benchTestDate: '',
  },
  {
    id: 'sp-002',
    title: 'Open Tulip Etched Shade — Magenta 4"',
    category: { id: 'col-2', name: 'Oil Lamp Shades' },
    shortDescription: 'Victorian and Edwardian oil lamp shade, beautifully etched in a deep magenta cranberry glass.',
    fullDescription: 'Open tulip form, hand-etched with a floral tulip pattern. Fits a standard 4" duplex gallery. Cranberry to white gradient — deep pink at the rim fading to frosted white at the base.',
    price: 175.00,
    compareAtPrice: null,
    sku: 'ACM-002',
    patent: '',
    stock: 5,
    status: 'active',
    collections: ['oil-lamp-shades'],
    tags: ['featured'],
    vendor: 'Acme Lamp & Sign Co.',
    images: [],
    sellWhenOutOfStock: false,
    netWeight: '0.5 kg',
    material: 'Glass',
    colour: 'Magenta',
    style: 'Victorian',
    brand: 'The Oil Lamp Company',
    vintage: 'Reproduction',
    burnerSize: '',
    fits: '4" duplex gallery',
    era: 'Victorian',
    powerSource: 'Oil',
    productType: 'Shade',
    condition: 'New',
    edition: '',
    workshop: '',
    benchTester: '',
    benchTestDate: '',
  },
  {
    id: 'sp-003',
    title: 'No. 2 Duplex Burner Wick',
    category: { id: 'col-6', name: 'Oil Lamp Wicks' },   // oil-lamp-wicks
    shortDescription: 'Cotton wick for No. 2 duplex oil lamp burners. Cut to fit, ready to install.',
    fullDescription: 'Cotton wick for No. 2 duplex oil lamp burners. Cut to fit, ready to install. Sourced to match original burner specifications.',
    price: 18.00,
    compareAtPrice: null,
    sku: 'ACM-011',
    patent: '',
    stock: 24,
    status: 'active',
    collections: ['oil-lamp-wicks'],
    tags: [],
    vendor: 'Acme Lamp & Sign Co.',
    images: [],
    sellWhenOutOfStock: false,
    netWeight: '0.05 kg',
    material: 'Cotton',
    colour: '',
    style: '',
    brand: '',
    vintage: '',
    burnerSize: 'No. 2',
    fits: 'No. 2 duplex burner',
    era: '',
    powerSource: 'Oil',
    productType: 'Wick',
    condition: 'New',
    edition: '',
    workshop: '',
    benchTester: '',
    benchTestDate: '',
  },
  {
    id: 'sp-004',
    title: 'Brass Gallery Ring — 4 inch',
    category: { id: 'col-5', name: 'Oil Lamp Spreaders' },   // oil-lamp-spreaders
    shortDescription: 'Antique-style brass gallery ring for 4" shade fit oil lamps.',
    fullDescription: 'Solid brass gallery ring. Fits standard 4" shade opening. Sourced from original Victorian lamp hardware.',
    price: 34.00,
    compareAtPrice: null,
    sku: 'ACM-008',
    patent: '',
    stock: 2,
    status: 'active',
    collections: ['oil-lamp-spreaders'],
    tags: [],
    vendor: 'Acme Lamp & Sign Co.',
    images: [],
    sellWhenOutOfStock: false,
    netWeight: '0.15 kg',
    material: 'Brass',
    colour: '',
    style: 'Victorian',
    brand: '',
    vintage: 'Antique',
    burnerSize: '',
    fits: '4" shade ring',
    era: 'Victorian',
    powerSource: '',
    productType: 'Spreader',
    condition: 'Good',
    edition: '',
    workshop: 'Acme Workshop',
    benchTester: 'PPlazan',
    benchTestDate: '2026-05-15',
  },
  {
    id: 'sp-005',
    title: 'Oil Lamp Collector — Volume 2',
    category: { id: 'col-4', name: 'Oil Lamp Books' },   // oil-lamp-books
    shortDescription: 'Reference guide on antique oil lamps, burners, and Victorian lighting history.',
    fullDescription: 'Essential reading for collectors and restorers. Covers burner types, shade identification, era dating, and restoration techniques.',
    price: 48.00,
    compareAtPrice: null,
    sku: 'ACM-015',
    patent: '',
    stock: 8,
    status: 'active',
    collections: ['oil-lamp-books'],
    tags: [],
    vendor: 'Acme Lamp & Sign Co.',
    images: [],
    sellWhenOutOfStock: false,
    netWeight: '0.6 kg',
    material: '',
    colour: '',
    style: '',
    brand: '',
    vintage: '',
    burnerSize: '',
    fits: '',
    era: '',
    powerSource: '',
    productType: 'Book',
    condition: 'New',
    edition: 'Second Edition',
    workshop: '',
    benchTester: '',
    benchTestDate: '',
  },
]

// ─── Collections ──────────────────────────────────────────────────────────────

export const mockCollections: AdminCollection[] = [
  { id: 'col-1', title: 'Oil Lamp Chimneys',       handle: 'oil-lamp-chimneys',       description: 'Antique and vintage oil lamp chimneys — plain, etched, and hand-painted glass.', productCount: 0, products: [] },
  { id: 'col-2', title: 'Oil Lamp Shades',         handle: 'oil-lamp-shades',         description: 'Victorian and Edwardian oil lamp shades — etched glass, floral, and ball shades.', productCount: 2, products: [] },
  { id: 'col-3', title: 'Oil Lamp Pressure Lamps', handle: 'oil-lamp-pressure-lamps', description: 'Complete antique pressure lamps and Aladdin-style oil lamps.', productCount: 0, products: [] },
  { id: 'col-4', title: 'Oil Lamp Books',          handle: 'oil-lamp-books',          description: 'Reference books and guides on antique oil lamps and Victorian lighting.', productCount: 1, products: [] },
  { id: 'col-5', title: 'Oil Lamp Spreaders',      handle: 'oil-lamp-spreaders',      description: 'Antique oil lamp spreaders, gallery rings, and burner hardware.', productCount: 1, products: [] },
  { id: 'col-6', title: 'Oil Lamp Wicks',          handle: 'oil-lamp-wicks',          description: 'Cotton wicks for antique oil lamps in all standard sizes.', productCount: 1, products: [] },
]

// ─── Customers ────────────────────────────────────────────────────────────────

export const mockCustomers: AdminCustomer[] = [
  { id: 'cust-001', name: 'Margaret Holloway', email: 'margaret@example.com',       phone: '+1 902 555 0142', address: '14 Elm Street',       city: 'Halifax',   province: 'NS', country: 'Canada', orders: 3, totalSpent: 724.07, joined: '2026-02-14' },
  { id: 'cust-002', name: 'James Whitfield',   email: 'james.whitfield@example.com',phone: '+1 902 555 0198', address: '7 Harbour View',      city: 'Dartmouth', province: 'NS', country: 'Canada', orders: 1, totalSpent: 212.31, joined: '2026-05-26' },
  { id: 'cust-003', name: 'Eleanor Vance',     email: 'eleanor.v@example.com',      phone: '+1 416 555 0177', address: '22 Queen Street W',   city: 'Toronto',   province: 'ON', country: 'Canada', orders: 2, totalSpent: 462.70, joined: '2026-01-08' },
  { id: 'cust-004', name: 'Robert Dunning',    email: 'rdunning@example.com',       phone: '+1 604 555 0131', address: '88 Granville St',     city: 'Vancouver', province: 'BC', country: 'Canada', orders: 1, totalSpent: 102.93, joined: '2026-05-24' },
  { id: 'cust-005', name: 'Patricia Lowry',    email: 'patricia.lowry@example.com', phone: '+1 514 555 0109', address: '3 Rue Saint-Denis',   city: 'Montreal',  province: 'QC', country: 'Canada', orders: 1, totalSpent: 62.40,  joined: '2026-05-22' },
  { id: 'cust-006', name: 'William Hartley',   email: 'w.hartley@example.com',      phone: '+1 780 555 0188', address: '51 Jasper Avenue',    city: 'Edmonton',  province: 'AB', country: 'Canada', orders: 1, totalSpent: 0,      joined: '2026-05-20' },
  { id: 'cust-007', name: 'Sylvia Brennan',    email: 'sylvia.b@example.com',       phone: '+1 902 555 0162', address: '9 Spring Garden Rd',  city: 'Halifax',   province: 'NS', country: 'Canada', orders: 2, totalSpent: 597.32, joined: '2026-03-01' },
  { id: 'cust-008', name: 'Thomas Ashby',      email: 'tashby@example.com',         phone: '+1 613 555 0145', address: '120 Wellington St',   city: 'Ottawa',    province: 'ON', country: 'Canada', orders: 1, totalSpent: 73.46,  joined: '2026-05-15' },
]

// ─── Revenue Stats ────────────────────────────────────────────────────────────

export const mockRevenueStats: RevenueStats = {
  today:        523.00,
  week:         3840.00,
  month:        14200.00,
  todayChange:  +6,
  weekChange:   +12,
  monthChange:  +8,
}

export const mockOrderCount = { today: 2, week: 11, month: 48 }
export const mockSessionCount = { week: 1240, weekChange: +12 }
export const mockConversionRate = { value: 3.9, change: -0.2 }

// ─── Chart Data (30 days) ─────────────────────────────────────────────────────

export const mockChartData: ChartDataPoint[] = [
  { date: 'Apr 28', revenue: 210,  orders: 1 },
  { date: 'Apr 29', revenue: 0,    orders: 0 },
  { date: 'Apr 30', revenue: 320,  orders: 2 },
  { date: 'May 1',  revenue: 480,  orders: 3 },
  { date: 'May 2',  revenue: 175,  orders: 1 },
  { date: 'May 3',  revenue: 0,    orders: 0 },
  { date: 'May 4',  revenue: 385,  orders: 2 },
  { date: 'May 5',  revenue: 620,  orders: 3 },
  { date: 'May 6',  revenue: 175,  orders: 1 },
  { date: 'May 7',  revenue: 258,  orders: 2 },
  { date: 'May 8',  revenue: 0,    orders: 0 },
  { date: 'May 9',  revenue: 190,  orders: 1 },
  { date: 'May 10', revenue: 412,  orders: 2 },
  { date: 'May 11', revenue: 175,  orders: 1 },
  { date: 'May 12', revenue: 730,  orders: 4 },
  { date: 'May 13', revenue: 0,    orders: 0 },
  { date: 'May 14', revenue: 320,  orders: 2 },
  { date: 'May 15', revenue: 73,   orders: 1 },
  { date: 'May 16', revenue: 350,  orders: 2 },
  { date: 'May 17', revenue: 0,    orders: 0 },
  { date: 'May 18', revenue: 385,  orders: 1 },
  { date: 'May 19', revenue: 520,  orders: 3 },
  { date: 'May 20', revenue: 212,  orders: 1 },
  { date: 'May 21', revenue: 0,    orders: 0 },
  { date: 'May 22', revenue: 62,   orders: 1 },
  { date: 'May 23', revenue: 440,  orders: 2 },
  { date: 'May 24', revenue: 103,  orders: 1 },
  { date: 'May 25', revenue: 231,  orders: 1 },
  { date: 'May 26', revenue: 212,  orders: 1 },
  { date: 'May 27', revenue: 258,  orders: 1 },
]

// ─── Top Products ─────────────────────────────────────────────────────────────

export const mockTopProducts: TopProduct[] = [
  { id: 'sp-001', title: 'Embossed Satin Glass Shade — Powder Blue', sku: 'ACM-001', unitsSold: 8,  revenue: 1400.00, collection: 'Oil Lamp Shades' },
  { id: 'sp-002', title: 'Open Tulip Etched Shade — Magenta',        sku: 'ACM-002', unitsSold: 6,  revenue: 1050.00, collection: 'Oil Lamp Shades' },
  { id: 'sp-005', title: 'Aladdin Pressure Lamp — Complete',         sku: 'ACM-005', unitsSold: 3,  revenue: 960.00,  collection: 'Oil Lamp Pressure Lamps' },
  { id: 'sp-004', title: 'Brass Gallery Ring — 4 inch',              sku: 'ACM-008', unitsSold: 12, revenue: 408.00,  collection: 'Oil Lamp Spreaders' },
  { id: 'sp-003', title: 'No. 2 Duplex Burner Wick',                 sku: 'ACM-011', unitsSold: 18, revenue: 324.00,  collection: 'Oil Lamp Wicks' },
]

// ─── Abandoned Checkouts ─────────────────────────────────────────────────────

export const mockAbandonedCheckouts: AbandonedCheckout[] = [
  { id: 'ab-001', customer: 'Anonymous',          email: '',                       items: 1, value: 175.00, abandonedAt: '2026-05-27T14:22:00Z' },
  { id: 'ab-002', customer: 'George Pembridge',   email: 'g.pembridge@example.com',items: 2, value: 348.00, abandonedAt: '2026-05-26T09:45:00Z' },
  { id: 'ab-003', customer: 'Anonymous',          email: '',                       items: 1, value: 48.00,  abandonedAt: '2026-05-25T18:10:00Z' },
]

// ─── Inventory Alerts ─────────────────────────────────────────────────────────

export const mockInventoryAlerts = mockAdminProducts.filter(p => p.stock <= 3)
