import { ChartDataPoint } from './types'

// ─── Chart Data (30 days) ─────────────────────────────────────────────────────

export const mockChartData: ChartDataPoint[] = [
  { date: 'Apr 28', revenue: 210,  orders: 1 },
  { date: 'Apr 29', revenue: 0,    orders: 0 },
  { date: 'Apr 30', revenue: 320,  orders: 2 },
  { date: 'May 1',  revenue: 480,  orders: 3 },
  { date: 'May 2',  revenue: 175,  orders: 1 },
  { date: 'May 3',  revenue: 0,    orders: 0 },
  { date: 'May 4',  revenue: 385,  orders: 2 },
  { date: 'May 5',  revenue: 620,  orders: 3 },
  { date: 'May 6',  revenue: 175,  orders: 1 },
  { date: 'May 7',  revenue: 258,  orders: 2 },
  { date: 'May 8',  revenue: 0,    orders: 0 },
  { date: 'May 9',  revenue: 190,  orders: 1 },
  { date: 'May 10', revenue: 412,  orders: 2 },
  { date: 'May 11', revenue: 175,  orders: 1 },
  { date: 'May 12', revenue: 730,  orders: 4 },
  { date: 'May 13', revenue: 0,    orders: 0 },
  { date: 'May 14', revenue: 320,  orders: 2 },
  { date: 'May 15', revenue: 73,   orders: 1 },
  { date: 'May 16', revenue: 350,  orders: 2 },
  { date: 'May 17', revenue: 0,    orders: 0 },
  { date: 'May 18', revenue: 385,  orders: 1 },
  { date: 'May 19', revenue: 520,  orders: 3 },
  { date: 'May 20', revenue: 212,  orders: 1 },
  { date: 'May 21', revenue: 0,    orders: 0 },
  { date: 'May 22', revenue: 62,   orders: 1 },
  { date: 'May 23', revenue: 440,  orders: 2 },
  { date: 'May 24', revenue: 103,  orders: 1 },
  { date: 'May 25', revenue: 231,  orders: 1 },
  { date: 'May 26', revenue: 212,  orders: 1 },
  { date: 'May 27', revenue: 258,  orders: 1 },
]
